// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupDQKjLVk57ZwKie38mY0WL5CAyV9HaI',
    appId: '1:93685497268:web:a824ed48890827810746e1',
    messagingSenderId: '93685497268',
    projectId: 'shopapp-9bcf6',
    authDomain: 'shopapp-9bcf6.firebaseapp.com',
    storageBucket: 'shopapp-9bcf6.firebasestorage.app',
    measurementId: 'G-2QGNGGK4QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnRX9mS-o-myhIQzzqhLLUdLBcTkHZJis',
    appId: '1:93685497268:android:eb0b91609a8ab4060746e1',
    messagingSenderId: '93685497268',
    projectId: 'shopapp-9bcf6',
    storageBucket: 'shopapp-9bcf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaTIyc1SVvDbdLuHHWmdAImozj2-dNlTw',
    appId: '1:93685497268:ios:6d1b5a7d66e70d7c0746e1',
    messagingSenderId: '93685497268',
    projectId: 'shopapp-9bcf6',
    storageBucket: 'shopapp-9bcf6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaTIyc1SVvDbdLuHHWmdAImozj2-dNlTw',
    appId: '1:93685497268:ios:6d1b5a7d66e70d7c0746e1',
    messagingSenderId: '93685497268',
    projectId: 'shopapp-9bcf6',
    storageBucket: 'shopapp-9bcf6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAupDQKjLVk57ZwKie38mY0WL5CAyV9HaI',
    appId: '1:93685497268:web:1c919597ed847c4a0746e1',
    messagingSenderId: '93685497268',
    projectId: 'shopapp-9bcf6',
    authDomain: 'shopapp-9bcf6.firebaseapp.com',
    storageBucket: 'shopapp-9bcf6.firebasestorage.app',
    measurementId: 'G-YMNGM6Z87F',
  );
}
